name: TruffleRuby Dev Builds
on:
  push:
    tags:
    - '*'
  schedule: # [10,15,19,23].map { |h| h-2 }.join(',')
  - cron: '0 8,13,17,21 * * *'
jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      if: github.event_name == 'schedule'

    - name: Clone TruffleRuby
      uses: actions/checkout@v2
      with:
        repository: eregon/truffleruby
        path: truffleruby
        ref: bd/bigsur
    - name: Set latest_commit
      id: latest_commit
      working-directory: truffleruby
      run: echo "::set-output name=commit::$(git rev-parse HEAD)"

    - name: Cancel if latest commit already built
      uses: actions/github-script@v2
      id: check_commit
      with:
        script: |
          const latestDevCommit = "${{ steps.latest_commit.outputs.commit }}"
          const { owner, repo } = context.repo
          let { data: release } = await github.repos.getLatestRelease({ owner, repo })
          const latestReleaseCommit = release.body.split('@')[1]
          console.log(`Latest Release commit: ${latestReleaseCommit}`)
          console.log(`Latest TruffleRuby commit: ${latestDevCommit}`)
          if (latestReleaseCommit === latestDevCommit) {
            console.log('Cancelling ...');
            const run_id = "${{ github.run_id }}";
            await github.actions.cancelWorkflowRun({ owner, repo, run_id });
            return 'stop'
          } else {
            return 'build'
          }
        result-encoding: string
    - name: Waiting for cancellation
      run: sleep 60
      if: steps.check_commit.outputs.result == 'stop'
    - name: Should build?
      run: test "${{ steps.check_commit.outputs.result }}" = "build"

    - name: Create artifact files
      run: |
        mkdir info
        echo "${{ steps.latest_commit.outputs.commit }}" > info/commit
    - uses: actions/upload-artifact@v1
      with:
        name: info
        path: info

  build:
    needs: [release]
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11.0 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: info
    - name: Set upload_info
      id: upload_info
      run: |
        echo "::set-output name=commit::$(cat info/commit)"
        echo "::set-output name=upload_url::$(cat info/upload_url)"

    - name: Setup system ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - run: echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV
      if: matrix.os == 'macos-latest'

    - name: Clone TruffleRuby
      uses: actions/checkout@v2
      with:
        repository: eregon/truffleruby
        ref: ${{ steps.upload_info.outputs.commit }}
    - name: Install JVMCI
      run: |
        tool/jt.rb install jvmci
        echo "JAVA_HOME=$(tool/jt.rb install jvmci)" >> $GITHUB_ENV
    - name: Install mx
      run: tool/jt.rb mx --version
    - name: Clone Graal
      uses: actions/checkout@v2
      with:
        repository: eregon/graal
        path: graal
        fetch-depth: 0
    - run: mv graal ..
    - run: tool/jt.rb mx sforceimports

    - run: tool/jt.rb build --env native

    - run: mkdir -p ~/.rubies
    - run: mv $(tool/jt.rb mx --env native standalone-home ruby) ~/.rubies/truffleruby-head
    - name: Create archive
      run: tar czf truffleruby-head-${{ matrix.os }}.tar.gz -C ~/.rubies truffleruby-head

    - name: Basic test
      run: ~/.rubies/truffleruby-head/bin/ruby --version
    - name: OpenSSL test
      run: ~/.rubies/truffleruby-head/bin/ruby -ropen-uri -e 'puts open("https://rubygems.org/") { |f| f.read(1024) }'
