name: Test
on: push
jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      if: github.event_name == 'schedule'

    - name: Clone TruffleRuby
      uses: actions/checkout@v2
      with:
        repository: eregon/truffleruby
        path: truffleruby
        ref: bd/bigsur
    - name: Set latest_commit
      id: latest_commit
      working-directory: truffleruby
      run: echo "::set-output name=commit::$(git rev-parse HEAD)"

    - name: Create artifact files
      run: |
        mkdir info
        echo "${{ steps.latest_commit.outputs.commit }}" > info/commit
    - uses: actions/upload-artifact@v1
      with:
        name: info
        path: info

  build:
    needs: [release]
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11.0 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: info
    - name: Set upload_info
      id: upload_info
      run: |
        echo "::set-output name=commit::$(cat info/commit)"
        echo "::set-output name=upload_url::$(cat info/upload_url)"

    - name: Setup system ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - run: echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV
      if: matrix.os == 'macos-latest'

    - name: Clone TruffleRuby
      uses: actions/checkout@v2
      with:
        repository: eregon/truffleruby
        ref: ${{ steps.upload_info.outputs.commit }}
    - name: Install JVMCI
      run: |
        tool/jt.rb install jvmci
        echo "JAVA_HOME=$(tool/jt.rb install jvmci)" >> $GITHUB_ENV
    - name: Install mx
      run: tool/jt.rb mx --version
    - name: Clone Graal
      uses: actions/checkout@v2
      with:
        repository: eregon/graal
        path: graal
        fetch-depth: 0
    - run: mv graal ..
    - run: tool/jt.rb mx sforceimports

    - run: tool/jt.rb build --env native

    - run: mkdir -p ~/.rubies
    - run: mv $(tool/jt.rb mx --env native standalone-home ruby) ~/.rubies/truffleruby-head
    - name: Create archive
      run: tar czf truffleruby-head-${{ matrix.os }}.tar.gz -C ~/.rubies truffleruby-head

    - name: Basic test
      run: ~/.rubies/truffleruby-head/bin/ruby --version
    - name: OpenSSL test
      run: ~/.rubies/truffleruby-head/bin/ruby -ropen-uri -e 'puts open("https://rubygems.org/") { |f| f.read(1024) }'
